spring:
  application:
    name: ClinicaMedica

  datasource:
    url: jdbc:mysql://localhost:3306/bancoTeste
    username: root
    password: 929305sp
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

    spring:
      jackson:
        time-zone: America/Sao_Paulo
